# Configuration for Alacritty, the GPU enhanced terminal emulator

[font]
# The font for regular text.
normal = { family = "Terminus", style = "Regular" }

# The font for bold text.
bold = { family = "Terminus", style = "Regular" }

# The font for italic text.
italic = { family = "Terminus", style = "Regular" }

# The font for bold italic text.
bold_italic = { family = "Terminus", style = "Regular" }

# Font size in points.
size = 15.0

