[font]
normal = { family = "0xProto Nerd Font", style = "Regular" }

bold = { family = "0xProto Nerd Font", style = "Bold" }

italic = { family = "0xProto Nerd Font", style = "Italic" }

bold_italic = { family = "0xProto Nerd Font", style = "Bold Italic" }

size = 12.0

